In [76]:
import torch
import numpy as np    # importing libraries

### Initializing a Tensor 

In [41]:
data = [[1, 2],[3, 4]]    #creating data
x_data = torch.tensor(data) # loading into  tensors 
x_data

tensor([[1, 2],
        [3, 4]])

In [42]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)  ## creating tensors from numpy arrays 
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [43]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")  # getting data from another tensor



Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [44]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.5827, 0.1357],
        [0.3036, 0.2714]]) 



In [45]:
shape = (2,4,)                    ## dimensions of the tensor 
rand_tensor = torch.rand(shape)   ##  Generating random tensors of that dimension
ones_tensor = torch.ones(shape)   ## tensor of all ones
zeros_tensor = torch.zeros(shape) ## tensor of all zeros 

In [46]:
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5712, 0.1269, 0.2390, 0.7154],
        [0.5558, 0.4126, 0.6498, 0.0200]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### Attributes of Tensor 

In [78]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")  #shape 
print(f"Datatype of tensor: {tensor.dtype}") # datatype
print(f"Device tensor is stored on: {tensor.device}") # device in which they are stored

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Operations on Tensors

In [48]:
tensor = torch.ones(3,3)
tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [49]:
tensor[:,1] =0  #slicing on the tensor
tensor

tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])

In [50]:
t1 = torch.cat([tensor,tensor,tensor],dim=1) # concatenating using 'cat'
t1

tensor([[1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.]])

### Arithmetic Operations

In [51]:
y1 = tensor
y2 = tensor.T ## getting the transpose of the tensor
y3 = torch.matmul(y1 ,y2 ) # matrix multiplications on the tensor
y3

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [52]:
y4 = torch.rand_like(y3) # gets a random array of same shape as y3
y4

tensor([[0.2416, 0.8576, 0.3581],
        [0.1266, 0.0632, 0.2968],
        [0.9830, 0.0511, 0.4153]])

In [53]:
torch.mul(tensor, tensor, out=y3) # matrix multiplications of tensors


tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])

### Single Element tensors

In [54]:
agg = tensor.sum()  # sum of the all elements in the tensor
agg
agg_item = agg.item() # convert the value into python numerical value
agg_item
print(agg_item,type(agg_item))

6.0 <class 'float'>


### In place operations

In [55]:
print(f'{tensor}\n')
tensor.add_(100)
tensor

tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])



tensor([[101., 100., 101.],
        [101., 100., 101.],
        [101., 100., 101.]])

### Bridge with NumPy

In [69]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()         ## changes in tensor affects numpy
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [72]:
t.add_(2)
t

tensor([3., 3., 3., 3., 3.])

In [73]:
n = np.ones(5)
t= torch.from_numpy(n)

In [77]:
np.add(n,1,out =n)     ## changes in numpy affects tensor

array([3., 3., 3., 3., 3.])